language: python
dist: xenial
cache: pip
env:
  global:
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: nightly
      env: TOXENV=py38
    - python: "3.7"
      env: TOXENV=flake8
    - python: "3.7"
      env: TOXENV=mypy
install:
  - pip install -U pip tox
  - pip install .
script:
  - tox -- -v
